export const filterData = [
  {
    id: 1,
    name: "label",
    value: "Price - Low to High",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 2,
    name: "label",
    value: "Price - High to Low",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 3,
    name: "label",
    value: "Total Phones - Low to High",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 4,
    name: "label",
    value: "Total Phones - High to Low",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 5,
    name: "label",
    value: "ASP - Low to High",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 6,
    name: "label",
    value: "ASP - High to Low",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 7,
    name: "label",
    value: "P4% - Low to High",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 8,
    name: "label",
    value: "P4% - High to Low",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 9,
    name: "label",
    value: "Apple% - Low to High",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 10,
    name: "label",
    value: "Apple% - High to Low",
    component_id: 1,
    component: "sort",
    type: "list",
  },
  {
    id: 11,
    name: "start",
    value: "0",
    component_id: 2,
    component: "apple%",
    type: "range",
  },
  {
    id: 12,
    name: "end",
    value: "10",
    component_id: 2,
    component: "apple%",
    type: "range",
  },
  {
    id: 13,
    name: "start",
    value: "0",
    component_id: 3,
    component: "p4%",
    type: "range",
  },
  {
    id: 14,
    name: "end",
    value: "10",
    component_id: 3,
    component: "p4%",
    type: "range",
  },
  {
    id: 15,
    name: "start",
    value: "1000",
    component_id: 4,
    component: "asp",
    type: "range",
  },
  {
    id: 16,
    name: "end",
    value: "50000",
    component_id: 4,
    component: "asp",
    type: "range",
  },
];
